server: 
  port: 3344 
  

spring: 
  profiles: 
    active: 
    - pro


---
server: 
  port: 8083
spring: 
  profiles: dev 
  application:
    name: springcloud-config-huayi-dev

---

server: 
  port: 8084
spring: 
  profiles: pro 
  application:
    name: springcloud-config-huayi-pro
 

