spring: 
  profiles: 
    active: 
    - pro


---

eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka 
  instance:
    instance-id: springcloud-dept8001 
    prefer-ip-address: true     
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    

info:
  app.name: huayi-springcloud
  company.name: www.91huayi.com
  build.artifactId: ${project.artifactId}$
  build.version: ${project.version}$

server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.huayi.pojo    
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       
    
spring:
   profiles: dev
   application:
    name: springcloud-config-client-dev
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver              
    url: jdbc:mysql://localhost:3306/cloudDB01              
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                          
      max-wait-millis: 200        


---

eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka 
  instance:
    instance-id: springcloud-dept8001 
    prefer-ip-address: true     
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    

info:
  app.name: huayi-springcloud
  company.name: www.91huayi.com
  build.artifactId: ${project.artifactId}$
  build.version: ${project.version}$

server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.huayi.pojo    
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       
    
spring:
   profiles: pro
   application:
    name: springcloud-config-client-pro 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver              
    url: jdbc:mysql://localhost:3306/cloudDB01              
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                          
      max-wait-millis: 200                             